-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgcS7EDzAbHSbgwLhdOqGdJmunPaFPIMXzjvHzLLXa/oSgCgYIKoZIzj0DAQehRANCAAQlAXcQpWaKCp07HOg9a75xOInxxg4A8F4kxPiLrFwDaZvPauFs0rz1Dagvon43VuSUA2mzEktrriZnfuoJA2q1
-----END PRIVATE KEY-----